---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      Style/StringLiterals:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Style/WordArray:
        Enabled: false
      Style/StringLiteralsInInterpolation:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false